### PR TITLE
[#97713486] Remove Dominic Baggot

### PR DESCRIPTION
**Pull request by mattbostock**
He has left GDS.

### CODE REVIEW

**Comment by issyl0** [comment]
:'(

**Comment by alexmuller** [comment]
[Hmm at line 84.](https://github.com/alphagov/ci-puppet/pull/305/files#diff-aaca6bd26a701d4f784001085ee76859R84)

**Comment by rjw1** [comment]
I think that may need an audit in general

**Comment by mattbostock** [comment]
Tekin is the next story in my list. But yes, there are others that can be removed here.

**Pull request merged**
