### PR TITLE
Delete all manifests related to ci-management-1

### PR DESCRIPTION
**Pull request by mattbostock**
We're going to remove the `ci-management-1` machine; it's used to retain
Graphite metrics about the CI environment but in reality these metrics
are rarely monitored.

/cc @rjw1 @jennyd 

* * *

I've tested this with a dry-run of Puppet:

```bash
matt➜~/govuk/ci-deployment(master)» fab production noop_deploy:remove_graphite
```

If this is merged, I'll raise a corresponding PR on the deployment repo.

### CODE REVIEW

**Comment by mattbostock** [comment]
_bump_

**Comment by jennyd** [comment]
Having these metrics hasn't prevented us running out of disk space on various `ci-slave-*` machines over the last few months, and we're no longer using `transition-logs-1` in a way which might fill up its disks unexpectedly (which was one of the reasons for adding the disk space monitoring - [we used to look at those metrics](https://github.com/alphagov/ci-puppet/pull/242#issuecomment-65058155)). I don't look at this graphite any more and I haven't heard anyone else mention it for a long time, so I'm happy with it going away.

**Comment by mattbostock** [comment]
Thanks @jennyd!

**Comment by mattbostock** [comment]
See related: https://github.gds/gds/ci-deployment/pull/76

**Pull request merged**
