### PR TITLE
Create new CI slave with PostgreSQL 9.5

### PR DESCRIPTION
**Pull request by surminus**
Adds the config to create a brand new CI slave with PostgreSQL 9.5. It's easier than upgrading a current CI slave, but we could also potentially just rebuild one.

### CODE REVIEW

**Comment by alexmuller** [comment]
I think it's better to rebuild one that exists already rather than creating a new one but I like this approach :+1:

**Comment by djsd123** [comment]
Given the shortcomings of the Postgresql module (Not supporting, upgrades) you did the sane thing imop. FFTM

**Comment by deanwilson** [comment]
@alexmuller I disagree. I'd rather build a new one, stop the old one, run with the new one and either do a full switch back to the old one if needed else delete it. Much easier than trying to upgrade in place and it leaves a roll back plan.

**Comment by alexmuller** [comment]
Happy with either approach! We have spare capacity in slaves that we could destroy one for the time it takes to rebuild it which would prevent us having strangely numbered machines. But I don't mind.

**Comment by surminus** [comment]
As discussed we're going to build a new one with a UID rather than a sequential number to get people used to ephemeral resources 😉

**Comment by boffbowsh** [comment]
e1ozaux

**Comment by alexmuller** [comment]
Just realised that this hostname breaks the [regular expression in `site.pp`](https://github.com/alphagov/ci-puppet/blob/17969e20dbde47008c9a4349178e400a2871c975/manifests/site.pp#L2-L3) 😞

**Comment by surminus** [comment]
@alexmuller does this adequately resolve it? https://github.com/alphagov/ci-puppet/pull/443/commits/4ee8338bc466a453d52d3577c96106851e511602

**Comment by alexmuller** [comment]
Looks good to me!

Machine role:

```
vagrant@ci-slave-eesh7:~$ puppet apply -e "notice(regsubst('ci-slave-1.internal', '^(.*)-[^\.]+\..*$', '\1'))"
Notice: Scope(Class[main]): ci-slave
vagrant@ci-slave-eesh7:~$ puppet apply -e "notice(regsubst('ci-slave-eeSh7.internal', '^(.*)-[^\.]+\..*$', '\1'))"
Notice: Scope(Class[main]): ci-slave
```

Machine ID:

```
vagrant@ci-slave-eesh7:~$ puppet apply -e "notice(regsubst('ci-slave-1.internal', '^.*-([^\.]+)\..*$', '\1'))"
Notice: Scope(Class[main]): 1
vagrant@ci-slave-eesh7:~$ puppet apply -e "notice(regsubst('ci-slave-eeSh7.internal', '^.*-([^\.]+)\..*$', '\1'))"
Notice: Scope(Class[main]): eeSh7
```

**Comment by alexmuller** [comment]
:+1:

**Pull request merged**
