### PR TITLE
Upgrade Ruby from 1.9.3 to 2.1.5

### PR DESCRIPTION
**Pull request by alexmuller**
1.9.3 is travelling in the direction of end-of-life, so upgrade to Ruby 2.

### CODE REVIEW

**Comment by alext** [comment]
Why 2.1.2?  We're putting 2.1.5 on the servers as well as 2.2.1...

**Comment by alexmuller** [comment]
I picked 2.1.2 because we have it in Boxen too, but maybe we should add 2.1.5 and 2.2.1 there as well.

**Comment by alext** [comment]
Given we install 2.1.5 on the ci-puppet slaves, it seems reasonable to use that.

Having said that, the current deploy scripts don't use rbenv when running puppet, they therefore use the system ruby, which is 1.9.3.

**Comment by alexmuller** [comment]
Agreed, I'll add 2.1.5 to boxen and amend this pull request.

**Comment by alexmuller** [comment]
Bumped this up to 2.1.5 after checking with @rjw1 that Puppet on the machines will actually use this version of Ruby.

**Comment by alext** [comment]
There's an interesting problem with the current deploy scripts.  If you ssh onto the box and run puppet, it will have the rbenv shims loaded, and therefore pick up the `.ruby-version` set ruby.  

When running it through fabric, this is not the case, and therefore means that the system ruby will be used (I think fabric starts a non-interactive shell meaning that `/etc/profile.d/rbenv.sh` isn't loaded).  I'm pretty sure that this was the cause of the oddness we were seeing with ci-slave-3 (before it was re-provisioned) whereby puppet would always fail when called from fabric, but would work when run manually.)

@rjw1 I'd be interested to know if something has changed that means this is no longer the case...

**Comment by rjw1** [comment]
@alext that may be true. admiiteldy this is possibly an easier fix than for the mirror boxes. I might look a this a bit more.

**Comment by rjw1** [comment]
closing while this gets reworked to actually use rbenv versions of ruby

**Pull request closed without merging**
